# Generated by Django 6.1.1 on 2026-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_householdmember_chore_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10),
        ),
    ]
